In [1]:
import numpy as np

In [8]:
arr1 = [1,2,3,4,5]
arr2 = [1,2,3,4,5]
arr1 = np.array(arr1)
arr2 = np.array(arr2)

In [9]:
arr1 + arr2 # - * / ^

array([ 2,  4,  6,  8, 10])

In [10]:
all(arr1) # np - .all()

True

In [11]:
any(arr1) #np - .any( )

True

In [12]:
np.random.randint(0,10,6)

array([0, 6, 9, 8, 6, 7], dtype=int32)

In [14]:
np.random.randint(0,10,(6, 2)) # Создает матрицу

array([[1, 3],
       [8, 2],
       [0, 3],
       [1, 8],
       [4, 9],
       [9, 3]], dtype=int32)

In [ ]:
np.dot(arr1, arr2) # Скалярное произведение

In [ ]:
linalg.solve # Решение уравнений

In [ ]:
a @ b # Перемножение матриц