In [1]:
import numpy as np

### Задачи 1-6 (13 баллов).

Для каждой из задач ниже приведите 2 реализации: одна без использования numpy, а вторая полностью векторизованная (**без использования циклов/map/list comprehension**). 

* __Задача 1__: Посчитать  сумму неотрицательных элементов на диагонали прямоугольной матрицы X. Если неотрицательных элементов на диагонали нет, то вернуть -1.

  **Пример:**
  
      Input: X = np.array([[-1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]])
      Output: 3

In [2]:
# 1.1

X = [[-1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]
def diagonal_py(X: list, ans = 0) -> int:
    i = len(X)
    j = len(X[0])
    if i > j:
        i, j = j, i
    for i in range(len(X[0])):
            if X[i][i] >=0:
                ans += X[i][i]
    return ans
print(diagonal_py(X))

3


In [3]:
# 1.2

X = np.array([[-1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]])
def diafonal_np(X: list) -> int:
    return np.diagonal(X)[np.diagonal(X)>0].sum()

* __Задача 2__: Даны два вектора x и y. Проверить, задают ли они одно и то же мультимножество.

   **Пример:**
      Input: x = [1, 2, 2, 4], y = [4, 2, 1, 2]
      Output: True

In [4]:
# 2.1
import copy
x = [1, 2, 2, 1]
y = [4, 2, 1, 2]

def multiset_py(x: list, y: list) -> bool:
    z = copy.deepcopy(x)
    if len(x) != len(y):
        return False
    for i in z:
        if i in y:
            x.remove(i)
            y.remove(i)
        else:
            return False
    return True

def multiset_py2(x: list, y: list) -> bool:
    return sorted(x) == sorted(y)
       

print(multiset_py(x, y))
print(multiset_py2(x, y))

False
False


In [5]:
# 2.2

x = [1, 2, 2, 4]
y = [4, 2, 1, 2]
def multiset_np(x: np.array, y: np.array) -> bool:
    return (np.sort(x) == np.sort(y)).all()
    
print(multiset_np(x, y))



True


* __Задача 3__: Найти максимальное прозведение соседних элементов в массиве x, таких что хотя бы один множитель в произведении делится на 3. Если таких произведений нет, то вернуть -1.

  **Пример**
  
      Input: x = [6, 2, 0, 3, 0, 0, 5, 7, 0]
      Output: 12

In [6]:
# 3.1

x = [7, 5, 8]
def multiplication_py(x: list, rec = float('-inf')) -> int:
    for i in range(0, len(x)-1):
        if x[i] % 3 == 0:
            rec = max(x[i]*x[i+1], rec)
    if rec == float('-inf'):
        return -1
    return rec


print(multiplication_py(x))

-1


In [7]:
# 3.2

x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])
def multiplication_np(x: np.array) -> int:
    muls = x[:-1] * x[1:]
    return np.max(muls[(x[:-1] % 3 == 0) | (x[1:] % 3 == 0)], initial=-1)

print(multiplication_np(x))



12


* __Задача 4__: Дан трёхмерный массив image, содержащий изображение, размера (height, width, num_channels), а также вектор весов weights длины num_channels. Сложить каналы изображения с указанными весами, и вернуть результат в виде матрицы размера (height, width). ***Обратите внимание, что в изображении может быть не три канала!***

  **Пример:**
  
      Input: image = [[[1, 1, 1], [2, 2, 2], [3, 3, 3]], [[4, 4, 4], [5, 5, 5], [6, 6, 6]], [[7, 7, 7], [8, 8, 8], [9, 9, 9]]], weights= [1, 2, 3]
      Output: [[6, 12, 18], [24, 30, 36], [42, 48, 54]]

  **Комментарий**:

  - В примере исходное изображение с тремя каналами, где по всем каналам значения равны [[1, 2, 3], [4, 5, 6], [7, 8, 9]].
  - После умножения первого канала на вес 1 получим значения для первого канала [[1, 2, 3], [4, 5, 6], [7, 8, 9]].
  - После умножения второго канала на вес 2 получим значения для второго канала [[2, 4, 6], [8, 10, 12], [14, 16, 18]].
  - После умножения третьего канала на вес 3 получим значения для третьего канала [[3, 6, 9], [12, 15, 18], [21, 24, 27]].
  - Если сложить полученное изображение поканально получим [[6, 12, 18], [24, 30, 36], [42, 48, 54]].


In [8]:
image = [[[1, 1, 1], [2, 2, 2], [3, 3, 3]], [[4, 4, 4], [5, 5, 5], [6, 6, 6]], [[7, 7, 7], [8, 8, 8], [9, 9, 9]]]
weights= [3, 2, 3]
def convert_image(image: list, weights: list) -> list:
    y = len(image)
    x = len(image[0])
    z = len(weights)
    ans = [[0 for i in range(x)] for j in range(y)]
    for i in range(y):
        for j in range(x):
            for channel in range(z):
                ans[i][j] += image[i][j][channel] * weights[channel]
    return ans

print(convert_image(image, weights))


[[8, 16, 24], [32, 40, 48], [56, 64, 72]]


In [9]:
image = np.array([[[1, 1, 1], [2, 2, 2], [3, 3, 3]], [[4, 4, 4], [5, 5, 5], [6, 6, 6]], [[7, 7, 7], [8, 8, 8], [9, 9, 9]]])
weights= np.array([3, 2, 3])
def convert_image_vec(image: np.array, weights: np.array) -> np.array:
    return np.tensordot(image, weights, axes=([2], [0]))
print(convert_image_vec(image, weights))

[[ 8 16 24]
 [32 40 48]
 [56 64 72]]


* __Задача 5__: Найти скалярное произведение между векторами x и y, заданными в формате RLE (Run-length encoding, кодирование длин серий). Каждый закодированный вектор представлен двумерным массивом, каждая строка которого имеет размерность 2, где первое число - элемент, а второе число - сколько раз элемент нужно повторить. Например, [[1,2], [2, 3], [3, 1]] соответствует веткору [1, 1, 2, 2, 2, 3]. В случае несовпадения длин исходных векторов вернуть -1.

  **Пример:**
  
      Input: x = [[1, 2], [2, 3], [3, 1]], y = [[1, 1], [0, 5]].
      Output: 1

In [10]:
#5.1
x = [[1, 2], [2, 3], [3, 1]]
y = [[1, 2], [0, 5]]

def scalar_mul_py(x: list, y: list):
    x1 = []
    y1 = []
    answer = 0
    for i in x:
        x1.extend([i[0]]*i[1])
    for i in y:
        y1.extend([i[0]]*i[1])
    if len(x1) != len(y1):
        return -1

    for i in range(len(x1)):
        answer += x1[i]*y1[i]
    return answer
        
scalar_mul_py(x,y)

-1

In [11]:
# 5.2
x = np.array([[1, 2], [2, 3], [3, 1]])
y = np.array([[1, 1], [0, 5]])

def scalar_mul_np(x: np.array, y:np.array):
    x1 = np.repeat(x[:, 0], x[:, 1])
    y1 = np.repeat(y[:, 0], y[:, 1])
    if x1.shape != y1.shape:
        return -1
    return np.dot(x1, y1)


scalar_mul_np(x, y)

np.int64(1)

### Задача 6.

*  Для каждой задачи сравните скорость работы невекторизованной и векторизованной реализации. Код генерации данных разных размеров и функция для замера времени работы функций уже написаны.
*  Сделайте выводы о времени работы функций.

In [12]:
import time
import numpy as np
import numpy as np

import functions_vectorised
import functions

In [13]:
# генерация данных

sum_non_neg_diag_data = []
for n in [10, 100, 1000, 10000]:
    X = np.random.randint(0, 3, (n, n))
    sum_non_neg_diag_data += [X]

are_multisets_equal_data = []
for n in [10, 100, 1000, 10000]:
    x = np.random.randint(0, 2, n)
    y = np.random.randint(0, 2, n)
    are_multisets_equal_data += [(x, y)]

max_prod_mod_3_data = []
for n in [10, 100, 1000, 10000]:
    x = np.random.randint(1, 100, n)
    max_prod_mod_3_data += [x]

convert_image_data = []
for n in [10, 100, 1000]:
    image = np.random.random((n, n, 10))
    weights = np.random.random(10)
    convert_image_data += [(image, weights)]

rle_scalar_data = []
for n in [10, 100, 1000, 10000]:
    x = np.random.randint(1, 3, (n, 2))
    y = np.random.randint(1, 3, (n, 2))
    shapes = np.random.randint(1, 3, n)
    x[:, 1] = shapes
    y[:, 1] = shapes

    rle_scalar_data += [(x, y)]

cosine_distance_data = []
for n in [10, 100]:
    X = np.random.random((n, n))
    Y = np.random.random((n, n))
    cosine_distance_data += [(X, Y)]

In [14]:
# функция для подсчета времени работы

def count_time(func, *data):
    tick = time.perf_counter()
    func(*data)
    return time.perf_counter() - tick

In [15]:
# получим время работы функций

# sum_non_neg_diag

sum_non_neg_diag_time = []
sum_non_neg_diag_vectorised_time = []

for X in sum_non_neg_diag_data:
   sum_non_neg_diag_time += [count_time(functions.sum_non_neg_diag, X.tolist())]
   sum_non_neg_diag_vectorised_time += [count_time(functions_vectorised.sum_non_neg_diag, X)]

# are_multisets_equal
# ...
                       
# max_prod_mod_3
# ...

# convert_image
# ...

# rle_scalar
# ...

# cosine_distance
# ...

AttributeError: module 'functions_vectorised' has no attribute 'sum_non_neg_diag'

**Выводы**: ВАШИ ВЫВОДЫ ЗДЕСЬ